Algoritmo "semnome"
//Faça um algoritmo que:
//a) Leia um número inteiro;
//b) Leia um segundo número inteiro;
//c) Efetue a adição dos dois valores;
//d) Apresente o valor calculado.
Var
   n1, n2: inteiro


Inicio
   //Entrada de dados
   escreva ("Insira o primeiro número inteiro: ")
   leia (n1)
   escreva ("Insira o segundo número inteiro: ")
   leia (n2)
   escreval ()
   escreval ()
   //Saída e processamento de dados
   escreva ("A soma dos dois valores é: ", n1+n2)

Fimalgoritmo