Algoritmo "semnome"
// Faça um algoritmo para calcular a área de uma circunferência, considerando a
//fórmula ÁREA = p * RAIO². Utilize as variáveis AREA e RAIO, a constante p (pi =
//3,14159) e os operadores aritméticos de multiplicação.
Var
   raio:real
   area:real
Inicio
   //Entrada de dados
   escreva ("Insira o raio da área: ")
   leia (raio)
   //Processamento de dados
   area<- (raio*raio) * 3.14

   //Saída de dados
   escreval ("A área é: ", area)

Fimalgoritmo