Algoritmo "Ler números e indicar qual é menor e maior"
// Programa feito por: Juan Soares Silva

//Dá pra unir todas as variáveis de um tipo em apenas uma linha de código.


Var

N1, N2: REAL


Inicio
escreva ("coloque o primeiro número: ")
//entrada de dados
leia (N1)
escreva ("coloque o segundo número :")
leia (N2)

//estrutura de decisão
se (N1>N2) então
//Saída de dados
escreval (N1, " maior que ",N2)
senao
escreva (N2, " maior que ",N1)
fimse


Fimalgoritmo