Algoritmo "semnome"
// Programa feito por: Juan Soares Silva
//Ler nome e sobrenome
Var
//
nome: caracter
sobrenome: caracter
n: caracter
Inicio
//Receptando informações
escreva("Digite o seu primeiro nome: ")
leia (nome)
escreva("Digite o seu sobrenome: ")
leia (sobrenome)

//processando informações
  n <- (nome +" "+ sobrenome)
  
//Saída da informação
 Escreval ("Bem vindo!!!")
 Escreval ("-------------")
 Escreva (n)



Fimalgoritmo